name: freebayes
channels:
  - defaults
  - bioconda
  - r
  - conda-forge
dependencies:
  - picard = 2.23.3 
  - gatk=3.8
  - samtools=1.4.1
  - snakemake=5.3.0
  #- pyyaml=3.11
  - bwa=0.7.17
  - trimmomatic=0.39
  - fastqc = 0.11.9
  - freebayes=1.3.2
  - fastp=0.20.1
  #- vcflib = 1.0.1

