name: freebayes
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - picard=2.23.3 
  - openjdk=9.0.7  
  - bioconda::samtools=1.9
  - snakemake=5.3.0
  - bwa=0.7.17
  - trimmomatic=0.39
  - fastqc = 0.11.9
  - freebayes=1.3.2
  - fastp=0.20.1

