---
tempdir: "temp/"                # where to store temporary files like trimmed fastq files
remove_workdir: FALSE             # turn to FALSE to remove it at the end of the analysis 
resultdir: "results/"            # directory with all results



# units to samples tsv file
units: "config/units.tsv"
        
# read quality trimming
fastp:
  qualified_quality_phred: 30         # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 
  maximum_length:          150        # global trimming option to a specified maximum length. Same for both paired reads.

# Genome statistics
deeptools:
  binsize: 100000 


## Genome reference assembly
refs:
  genome:  "config/refs/S_lycopersicum_chromosomes.4.00.chrom1.fa"


